### ISSUE TITLE
RuntimeError: The expanded size of the tensor

### ISSUE THREAD

**Issue by edanweis** [DrewThomasson/ebook_to_audiobook_styletts#1]
I run the code on a simple .doc and get error

```
Converting chapters to audio:   0%|                                                                                                                                                           | 0/1 [00:23<?, ?it/s]
Traceback (most recent call last):
  File "/sd/ebook2audiobookSTYLETTS2/styletts_to_ebook.py", line 340, in <module>
    convert_chapters_to_audio(chapters_directory, output_audio_directory, target_voice)
  File "/sd/ebook2audiobookSTYLETTS2/styletts_to_ebook.py", line 313, in convert_chapters_to_audio
    my_tts.inference(chapter_text, output_wav_file=output_file_path)
  File "/sd/miniconda3/envs/styletts2/lib/python3.11/site-packages/styletts2/tts.py", line 212, in inference
    return self.long_inference(text,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sd/miniconda3/envs/styletts2/lib/python3.11/site-packages/styletts2/tts.py", line 341, in long_inference
    segment_output, prev_s = self.long_inference_segment(text_segment,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sd/miniconda3/envs/styletts2/lib/python3.11/site-packages/styletts2/tts.py", line 394, in long_inference_segment
    bert_dur = self.model.bert(tokens, attention_mask=(~text_mask).int())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sd/miniconda3/envs/styletts2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sd/miniconda3/envs/styletts2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sd/miniconda3/envs/styletts2/lib/python3.11/site-packages/styletts2/Utils/PLBERT/util.py", line 9, in forward
    outputs = super().forward(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sd/miniconda3/envs/styletts2/lib/python3.11/site-packages/transformers/models/albert/modeling_albert.py", line 719, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The expanded size of the tensor (549) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [1, 549].  Tensor sizes: [1, 512]
```

**Comment by edanweis** [comment]
Ooops, .doc doesnt work. It worked with a txt

**Comment by DrewThomasson** [comment]
Nice! Good to hear! 

I'll mark this as complete and make sure the readme says the right supported file formats 

:)

**Comment by AlexCuan** [comment]
I'm having the same error with an epub file:


Traceback (most recent call last):
  File "/home/alex/PycharmProjects/ebook2audiobookSTYLETTS2/styletts_to_ebook.py", line 429, in <module>
    convert_chapters_to_audio(chapters_directory, output_audio_directory, target_voice)
  File "/home/alex/PycharmProjects/ebook2audiobookSTYLETTS2/styletts_to_ebook.py", line 352, in convert_chapters_to_audio
    my_tts.inference(chapter_text, output_wav_file=output_file_path)
  File "/home/alex/PycharmProjects/ebook2audiobookSTYLETTS2/.venv/lib/python3.12/site-packages/styletts2/tts.py", line 212, in inference
    return self.long_inference(text,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/PycharmProjects/ebook2audiobookSTYLETTS2/.venv/lib/python3.12/site-packages/styletts2/tts.py", line 341, in long_inference
    segment_output, prev_s = self.long_inference_segment(text_segment,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/PycharmProjects/ebook2audiobookSTYLETTS2/.venv/lib/python3.12/site-packages/styletts2/tts.py", line 394, in long_inference_segment
    bert_dur = self.model.bert(tokens, attention_mask=(~text_mask).int())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/PycharmProjects/ebook2audiobookSTYLETTS2/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/PycharmProjects/ebook2audiobookSTYLETTS2/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/PycharmProjects/ebook2audiobookSTYLETTS2/.venv/lib/python3.12/site-packages/styletts2/Utils/PLBERT/util.py", line 9, in forward
    outputs = super().forward(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/PycharmProjects/ebook2audiobookSTYLETTS2/.venv/lib/python3.12/site-packages/transformers/models/albert/modeling_albert.py", line 709, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The expanded size of the tensor (538) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [1, 538].  Tensor sizes: [1, 512]

**Comment by DrewThomasson** [comment]
Anyway I could get that epub file to test out on my end?

**Comment by AlexCuan** [comment]
> Anyway I could get that epub file to test out on my end?

Of course. I'll attach it. In addition, I'll leave some other info if it helps:

Graphics card: RTX 2060 Mobile 6gb Vram
Proccessor: Rizen 7 4800H
Ram: 16gb 3200MHz
OS: Manjaro 24.0.2 
Kernel: 6.6.32-1
[ebook.zip](https://github.com/user-attachments/files/16125895/ebook.zip)

**Comment by DrewThomasson** [comment]
Try it as a txt file instead of a epub and see if that works, in the meantime I'll test your file when I get an opening

:)

**Comment by AlexCuan** [comment]
> Try it as a txt file instead of a epub and see if that works, in the meantime I'll test your file when I get an opening
> 
> :)

Same thing: https://pastebin.com/JLkmR7r8
I think the problem is with the tokenizer. I'm working right now with another e-book and still getting the same error 🤷🏻
I don't know what's the problem if I tried at first with the test EPUB and everything went just fine.
